# Everything that's downloaded after cloning Chromium goes here.
# It will not work from main downloads.ini
[search_engines_data]
version = 202609082320
url = https://github.com/imputnet/helium-nonfree-assets/releases/download/%(version)s/nonfree-search-engines-data-%(version)s.tar.gz
download_filename = nonfree-search-engines-data-%(version)s.tar.gz
sha256 = 2a8d63af41454446d64bb5f19786d908419265f152adaff087132d8e0cda51a7
output_path = ./third_party/search_engines_data/resources_internal

[onboarding]
version = 202608281912
url = https://github.com/imputnet/helium-onboarding/releases/download/%(version)s/helium-onboarding-%(version)s.tar.gz
download_filename = onboarding-page-%(version)s.tar.gz
sha256 = 1187602539990849e4790e3e4b91b223ebf836f0a56cbf28ee05dcac127a6d65
output_path = ./components/helium_onboarding

# If you are bumping this, you *NEED* to re-strip the assets.json
# file *every time* by using `devutils/clear-ublock-assets.js`.
[ublock_origin]
version = 1.74.0-2
url = https://github.com/imputnet/uBlock/releases/download/%(version)s/uBlock0_%(version)s.chromium.zip
sha256 = e96af922ff6a22a748e85b5685503f3ed2b96f7ed46ca82a60084b1363d91eb0
download_filename = ublock-origin-%(version)s.zip
output_path = third_party/ublock
strip_leading_dirs = uBlock0.chromium
